// written by scripts/children.ts from the engine's layout
/** For every type of node a built-in plan answers with, the fields that hold a node or a list of nodes: what a walk follows. A document plan's `children` adds the host's. */
export const children = frozen({
	Program: ['body'],
	Identifier: [],
	PrivateIdentifier: [],
	Literal: [],
	TemplateLiteral: ['expressions', 'quasis'],
	TemplateElement: [],
	TaggedTemplateExpression: ['tag', 'quasi'],
	ThisExpression: [],
	Super: [],
	ArrayExpression: ['elements'],
	ObjectExpression: ['properties'],
	Property: ['key', 'value'],
	SpreadElement: ['argument'],
	UnaryExpression: ['argument'],
	UpdateExpression: ['argument'],
	BinaryExpression: ['left', 'right'],
	LogicalExpression: ['left', 'right'],
	AssignmentExpression: ['left', 'right'],
	ConditionalExpression: ['test', 'consequent', 'alternate'],
	MemberExpression: ['object', 'property'],
	CallExpression: ['callee', 'arguments'],
	ChainExpression: ['expression'],
	NewExpression: ['callee', 'arguments'],
	SequenceExpression: ['expressions'],
	ArrowFunctionExpression: ['params', 'body'],
	FunctionExpression: ['id', 'params', 'body'],
	FunctionDeclaration: ['id', 'params', 'body'],
	ClassExpression: ['id', 'superClass', 'body'],
	ClassDeclaration: ['id', 'superClass', 'body'],
	ClassBody: ['body'],
	MethodDefinition: ['key', 'value'],
	PropertyDefinition: ['key', 'value'],
	AccessorProperty: ['key', 'value'],
	StaticBlock: ['body'],
	YieldExpression: ['argument'],
	AwaitExpression: ['argument'],
	MetaProperty: ['meta', 'property'],
	ImportExpression: ['source', 'options'],
	ObjectPattern: ['properties'],
	ArrayPattern: ['elements'],
	RestElement: ['argument'],
	AssignmentPattern: ['left', 'right'],
	ExpressionStatement: ['expression'],
	BlockStatement: ['body'],
	EmptyStatement: [],
	DebuggerStatement: [],
	WithStatement: ['object', 'body'],
	ReturnStatement: ['argument'],
	LabeledStatement: ['body', 'label'],
	BreakStatement: ['label'],
	ContinueStatement: ['label'],
	IfStatement: ['test', 'consequent', 'alternate'],
	SwitchStatement: ['discriminant', 'cases'],
	SwitchCase: ['consequent', 'test'],
	ThrowStatement: ['argument'],
	TryStatement: ['block', 'handler', 'finalizer'],
	CatchClause: ['param', 'body'],
	WhileStatement: ['test', 'body'],
	DoWhileStatement: ['body', 'test'],
	ForStatement: ['init', 'test', 'update', 'body'],
	ForInStatement: ['left', 'right', 'body'],
	ForOfStatement: ['left', 'right', 'body'],
	VariableDeclaration: ['declarations'],
	VariableDeclarator: ['id', 'init'],
	ImportDeclaration: ['specifiers', 'source', 'attributes'],
	ImportSpecifier: ['imported', 'local'],
	ImportDefaultSpecifier: ['local'],
	ImportNamespaceSpecifier: ['local'],
	ImportAttribute: ['key', 'value'],
	ExportNamedDeclaration: ['declaration', 'specifiers', 'source', 'attributes'],
	ExportSpecifier: ['local', 'exported'],
	ExportDefaultDeclaration: ['declaration'],
	ExportAllDeclaration: ['exported', 'source', 'attributes'],
	TSTypeAnnotation: ['typeAnnotation'],
	TSAnyKeyword: [],
	TSBooleanKeyword: [],
	TSBigIntKeyword: [],
	TSNeverKeyword: [],
	TSNumberKeyword: [],
	TSObjectKeyword: [],
	TSStringKeyword: [],
	TSSymbolKeyword: [],
	TSUndefinedKeyword: [],
	TSUnknownKeyword: [],
	TSVoidKeyword: [],
	TSNullKeyword: [],
	TSIntrinsicKeyword: [],
	TSThisType: [],
	TSTypePredicate: ['parameterName', 'typeAnnotation'],
	TSTypeReference: ['typeName', 'typeArguments'],
	TSQualifiedName: ['left', 'right'],
	TSTypeParameterInstantiation: ['params'],
	TSTypeParameterDeclaration: ['params'],
	TSTypeParameter: ['constraint', 'default'],
	TSFunctionType: ['typeParameters', 'parameters', 'typeAnnotation'],
	TSConstructorType: ['typeParameters', 'parameters', 'typeAnnotation'],
	TSUnionType: ['types'],
	TSIntersectionType: ['types'],
	TSTypeOperator: ['typeAnnotation'],
	TSInferType: ['typeParameter'],
	TSLiteralType: ['literal'],
	TSImportType: ['argument', 'qualifier', 'typeArguments'],
	TSTypeQuery: ['exprName', 'typeArguments'],
	TSMappedType: ['typeParameter', 'nameType', 'typeAnnotation'],
	TSTypeLiteral: ['members'],
	TSNamedTupleMember: ['label', 'elementType'],
	TSOptionalType: ['typeAnnotation'],
	TSRestType: ['typeAnnotation'],
	TSTupleType: ['elementTypes'],
	TSParenthesizedType: ['typeAnnotation'],
	TSArrayType: ['elementType'],
	TSIndexedAccessType: ['objectType', 'indexType'],
	TSConditionalType: ['checkType', 'extendsType', 'trueType', 'falseType'],
	TSIndexSignature: ['parameters', 'typeAnnotation'],
	TSCallSignatureDeclaration: ['typeParameters', 'parameters', 'typeAnnotation'],
	TSConstructSignatureDeclaration: ['typeParameters', 'parameters', 'typeAnnotation'],
	TSMethodSignature: ['key', 'typeParameters', 'parameters', 'typeAnnotation'],
	TSPropertySignature: ['key', 'typeAnnotation'],
	TSInterfaceDeclaration: ['id', 'typeParameters', 'extends', 'body'],
	TSInterfaceBody: ['body'],
	TSInterfaceHeritage: ['expression', 'typeArguments'],
	TSClassImplements: ['expression', 'typeArguments'],
	TSEnumDeclaration: ['id', 'members'],
	TSEnumMember: ['id', 'initializer'],
	TSModuleDeclaration: ['id', 'body'],
	TSModuleBlock: ['body'],
	TSTypeAliasDeclaration: ['id', 'typeParameters', 'typeAnnotation'],
	TSImportEqualsDeclaration: ['id', 'moduleReference'],
	TSExternalModuleReference: ['expression'],
	TSExportAssignment: ['expression'],
	TSNamespaceExportDeclaration: ['id'],
	TSDeclareFunction: ['id', 'params'],
	TSDeclareMethod: ['params'],
	TSAsExpression: ['expression', 'typeAnnotation'],
	TSSatisfiesExpression: ['expression', 'typeAnnotation'],
	TSNonNullExpression: ['expression'],
	TSTypeAssertion: ['typeAnnotation', 'expression'],
	TSTypeCastExpression: ['expression', 'typeAnnotation'],
	TSInstantiationExpression: ['expression', 'typeArguments'],
	TSParameterProperty: ['parameter'],
	Decorator: ['expression'],
} as const);

/** The fields TypeScript may add to a node of any type, holding nodes: annotations, type parameters and arguments, what a class implements, decorators. */
export const extras = Object.freeze(['typeAnnotation', 'returnType', 'typeParameters', 'typeArguments', 'superTypeArguments', 'implements', 'decorators'] as const);

export function frozen<T extends Readonly<Record<string, readonly string[]>>>(table: T): T {
	for (const fields of Object.values(table)) Object.freeze(fields);
	return Object.freeze(table);
}
