/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A source held with its options, so many parses out of it pay for its tables once. */
export declare class Source {
  constructor(source: string, options?: Options | undefined | null)
  /** The whole source, or the program spanning `start..end` of it. */
  parse(start?: number | undefined | null, end?: number | undefined | null): string
  /** `until` is `"as"` when the host's `as` follows the expression. */
  parseExpressionAt(offset: number, until?: string | undefined | null): string
  parsePatternAt(offset: number): string
  parseParamsAt(offset: number): string
  parseStatementAt(offset: number): string
}

export interface Options {
  /** `"script"` (the default, as in acorn) or `"module"`. */
  sourceType?: string
  typescript?: boolean
  /** With `typescript`: erase it from the output. */
  erase?: boolean
  comments?: boolean
  locations?: boolean
  preserveParens?: boolean
  allowReturnOutsideFunction?: boolean
  allowAwaitOutsideFunction?: boolean
  allowSuperOutsideMethod?: boolean
  allowUndeclaredExports?: boolean
  /** `"as"`: the host's `as` follows the expression, which ends at the last top-level one. */
  until?: string
}

export declare function parse(source: string, options?: Options | undefined | null): string

export declare function parseExpressionAt(source: string, offset: number, options?: Options | undefined | null): string

export declare function parseParamsAt(source: string, offset: number, options?: Options | undefined | null): string

export declare function parsePatternAt(source: string, offset: number, options?: Options | undefined | null): string

export declare function parseStatementAt(source: string, offset: number, options?: Options | undefined | null): string
