/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Options {
  /** `"module"` or `"script"`; a module by default. */
  sourceType?: string
  typescript?: boolean
  comments?: boolean
  preserveParens?: boolean
  allowReturnOutsideFunction?: boolean
  allowAwaitOutsideFunction?: boolean
  allowSuperOutsideMethod?: boolean
  allowUndeclaredExports?: boolean
}

export declare function parse(source: string, options?: Options | undefined | null): string

export declare function parseExpressionAt(source: string, offset: number, options?: Options | undefined | null): string

export declare function parseParamsAt(source: string, offset: number, options?: Options | undefined | null): string

export declare function parsePatternAt(source: string, offset: number, options?: Options | undefined | null): string

export declare function parseStatementAt(source: string, offset: number, options?: Options | undefined | null): string
