[package]
name = "teasel-node"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
teasel = { path = "../.." }
napi = { version = "3", default-features = false, features = ["napi9", "compat-mode"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"
