// Regenerates src/unicode.rs from the Unicode Character Database.
// Usage: bun scripts/unicode.js [version]

const version = process.argv[2] ?? '17.0.0';
const url = `https://www.unicode.org/Public/${version}/ucd/DerivedCoreProperties.txt`;
const text = await (await fetch(url)).text();

function ranges(property) {
	const out = [];
	for (const line of text.split('\n')) {
		const m = line.match(/^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)/);
		if (!m || m[3] !== property) continue;
		const start = parseInt(m[1], 16);
		const end = m[2] ? parseInt(m[2], 16) : start;
		if (end < 0x80) continue;
		out.push([Math.max(start, 0x80), end]);
	}
	out.sort((a, b) => a[0] - b[0]);
	const merged = [];
	for (const r of out) {
		const last = merged.at(-1);
		if (last && r[0] <= last[1] + 1) last[1] = Math.max(last[1], r[1]);
		else merged.push(r);
	}
	return merged;
}

function table(name, rs) {
	const rows = [];
	for (let i = 0; i < rs.length; i += 4) {
		rows.push('\t' + rs.slice(i, i + 4).map(([a, b]) => `(0x${a.toString(16)}, 0x${b.toString(16)})`).join(', ') + ',');
	}
	return `static ${name}: &[(u32, u32)] = &[\n${rows.join('\n')}\n];\n`;
}

const start = ranges('ID_Start');
const cont = ranges('ID_Continue');

const src = `// Generated by scripts/unicode.js from Unicode ${version}. Do not edit.

pub const VERSION: &str = "${version}";

${table('ID_START', start)}
${table('ID_CONTINUE', cont)}
fn lookup(table: &[(u32, u32)], c: u32) -> bool {
	table
		.binary_search_by(|&(lo, hi)| {
			if c < lo {
				std::cmp::Ordering::Greater
			} else if c > hi {
				std::cmp::Ordering::Less
			} else {
				std::cmp::Ordering::Equal
			}
		})
		.is_ok()
}

pub fn is_id_start(c: char) -> bool {
	if c.is_ascii() {
		return c.is_ascii_alphabetic();
	}
	lookup(ID_START, c as u32)
}

pub fn is_id_continue(c: char) -> bool {
	if c.is_ascii() {
		return c.is_ascii_alphanumeric();
	}
	lookup(ID_CONTINUE, c as u32)
}
`;

await Bun.write(new URL('../src/unicode.rs', import.meta.url), src);
console.log(`ID_Start ${start.length} ranges, ID_Continue ${cont.length} ranges`);
