// Regenerates src/lexer/unicode.rs from the Unicode Character Database.
// Usage: node scripts/unicode.js [version]
import { writeFileSync } from 'node:fs';

const version = process.argv[2] ?? '17.0.0';
const url = `https://www.unicode.org/Public/${version}/ucd/DerivedCoreProperties.txt`;
const text = await (await fetch(url)).text();

const LAST = 0x110000;
function members(property) {
	const set = new Uint8Array(LAST);
	for (const line of text.split('\n')) {
		const m = line.match(/^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)/);
		if (!m || m[3] !== property) continue;
		const start = parseInt(m[1], 16);
		const end = m[2] ? parseInt(m[2], 16) : start;
		for (let c = Math.max(start, 0x80); c <= end; c++) set[c] = 1;
	}
	return set;
}

// A three-level trie over 64-bit chunks, the layout of rustc's own tables: code points below
// 0x800 index a chunk directly, the rest of the plane goes through one byte of indirection, and
// the astral planes through two. Every lookup is at most three loads and no branches on the data.
function trie(set) {
	const chunk = (i) => {
		let lo = 0, hi = 0;
		for (let b = 0; b < 32; b++) {
			if (set[i * 64 + b]) lo |= 1 << b;
			if (set[i * 64 + 32 + b]) hi |= 1 << b;
		}
		return [lo >>> 0, hi >>> 0];
	};
	const dedup = () => {
		const list = [], index = new Map();
		return { list, of: (key, value) => index.get(key) ?? (index.set(key, list.push(value) - 1), list.length - 1) };
	};
	const r1 = Array.from({ length: 32 }, (_, i) => chunk(i));
	const r3 = dedup(), r2 = [];
	for (let i = 32; i < 0x400; i++) r2.push(r3.of(String(chunk(i)), chunk(i)));
	const r6 = dedup(), groups = dedup(), r4 = [];
	for (let plane = 0; plane < 256; plane++) {
		const group = [];
		for (let j = 0; j < 64; j++) {
			const i = 0x400 + plane * 64 + j;
			group.push(r6.of(String(chunk(i)), chunk(i)));
		}
		r4.push(groups.of(String(group), group));
	}
	const r5 = groups.list.flat();
	for (const [name, list] of [['r3', r3.list], ['r5', groups.list], ['r6', r6.list]]) {
		if (list.length > 256) throw new Error(`${name} needs ${list.length} entries, more than a byte indexes`);
	}
	const has = (c) => {
		const bit = ([lo, hi]) => (((c & 32 ? hi : lo) >>> (c & 31)) & 1) === 1;
		if (c < 0x800) return bit(r1[c >> 6]);
		if (c < 0x10000) return bit(r3.list[r2[(c >> 6) - 32]]);
		const leaf = r5[(r4[(c >> 12) - 16] << 6) | ((c >> 6) & 63)];
		return bit(r6.list[leaf]);
	};
	for (let c = 0; c < LAST; c++) if (has(c) !== (set[c] === 1)) throw new Error(`trie disagrees at ${c.toString(16)}`);
	return { r1, r2, r3: r3.list, r4, r5, r6: r6.list };
}

const start = trie(members('ID_Start'));
const cont = trie(members('ID_Continue'));

const rows = (items, per, render) => {
	const out = [];
	for (let i = 0; i < items.length; i += per) out.push('\t\t' + items.slice(i, i + per).map(render).join(', ') + ',');
	return out.join('\n');
};
const u64 = ([lo, hi]) => `0x${hi.toString(16).padStart(8, '0')}${lo.toString(16).padStart(8, '0')}`;
const rust = (name, t) => `#[rustfmt::skip]
static ${name}: Trie = Trie {
	r1: [
${rows(t.r1, 4, u64)}
	],
	r2: [
${rows(t.r2, 32, String)}
	],
	r3: &[
${rows(t.r3, 4, u64)}
	],
	r4: [
${rows(t.r4, 32, String)}
	],
	r5: &[
${rows(t.r5, 32, String)}
	],
	r6: &[
${rows(t.r6, 4, u64)}
	],
};
`;

const src = `// Generated by scripts/unicode.js from Unicode ${version}. Do not edit.

struct Trie {
	r1: [u64; 32],
	r2: [u8; 992],
	r3: &'static [u64],
	r4: [u8; 256],
	r5: &'static [u8],
	r6: &'static [u64],
}

impl Trie {
	#[inline]
	fn contains(&self, c: u32) -> bool {
		let chunk = if c < 0x800 {
			self.r1[(c >> 6) as usize]
		} else if c < 0x10000 {
			self.r3[self.r2[(c >> 6) as usize - 32] as usize]
		} else {
			let group = self.r4[(c >> 12) as usize - 16] as usize;
			self.r6[self.r5[(group << 6) | ((c >> 6) as usize & 63)] as usize]
		};
		(chunk >> (c & 63)) & 1 == 1
	}
}

${rust('ID_START', start)}
${rust('ID_CONTINUE', cont)}
pub(crate) fn is_id_start(c: char) -> bool {
	if c.is_ascii() {
		return c.is_ascii_alphabetic() || c == '$' || c == '_';
	}
	ID_START.contains(c as u32)
}

pub(crate) fn is_id_continue(c: char) -> bool {
	if c.is_ascii() {
		return c.is_ascii_alphanumeric() || c == '$' || c == '_';
	}
	ID_CONTINUE.contains(c as u32)
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	#[rustfmt::skip]
	fn every_level_answers() {
		for (c, start, cont) in [
			('a', true, true), ('1', false, true), ('$', true, true), ('-', false, false),
			('\\u{aa}', true, true), ('\\u{b7}', false, true), ('\\u{d7}', false, false),
			('\\u{2c1}', true, true), ('\\u{300}', false, true), ('\\u{37e}', false, false),
			('\\u{4e00}', true, true), ('\\u{200c}', false, true), ('\\u{fffd}', false, false),
			('\\u{10000}', true, true), ('\\u{1d4b3}', true, true), ('\\u{1f600}', false, false),
			('\\u{e0100}', false, true), ('\\u{10ffff}', false, false),
		] {
			assert_eq!(is_id_start(c), start, "start of {c:?}");
			assert_eq!(is_id_continue(c), cont, "continue of {c:?}");
		}
	}
}
`;
writeFileSync(new URL('../src/lexer/unicode.rs', import.meta.url), src);
console.log(`ID_Start: r3 ${start.r3.length}, r5 groups ${start.r5.length / 64}, r6 ${start.r6.length}; ID_Continue: r3 ${cont.r3.length}, r5 groups ${cont.r5.length / 64}, r6 ${cont.r6.length}`);
