use crate::interner::StrId;

#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct Token {
	pub(crate) kind: TokenKind,
	pub(crate) start: u32,
	pub(crate) end: u32,
	pub(crate) newline_before: bool,
	/// An identifier or keyword written with a unicode escape.
	pub(crate) escaped: bool,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) enum TokenKind {
	Eof,
	Ident(StrId),
	PrivateName(StrId),
	Keyword(Keyword),
	Number(f64),
	BigInt,
	String(StrId),
	Template {
		cooked: Option<StrId>,
		raw: StrId,
		tail: bool,
	},
	RegExp {
		pattern: StrId,
		flags: StrId,
	},

	BraceL,
	BraceR,
	ParenL,
	ParenR,
	BracketL,
	BracketR,
	Semi,
	Comma,
	Dot,
	Ellipsis,
	Question,
	QuestionDot,
	Colon,
	Arrow,
	Backquote,
	At,

	Eq,
	PlusEq,
	MinusEq,
	StarEq,
	SlashEq,
	PercentEq,
	StarStarEq,
	LtLtEq,
	GtGtEq,
	GtGtGtEq,
	AmpEq,
	PipeEq,
	CaretEq,
	AmpAmpEq,
	PipePipeEq,
	QuestionQuestionEq,

	EqEq,
	BangEq,
	EqEqEq,
	BangEqEq,
	Lt,
	Gt,
	LtEq,
	GtEq,
	LtLt,
	GtGt,
	GtGtGt,
	Plus,
	Minus,
	Star,
	Slash,
	Percent,
	StarStar,
	Amp,
	Pipe,
	Caret,
	AmpAmp,
	PipePipe,
	QuestionQuestion,
	Bang,
	Tilde,
	PlusPlus,
	MinusMinus,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Keyword {
	Break,
	Case,
	Catch,
	Class,
	Const,
	Continue,
	Debugger,
	Default,
	Delete,
	Do,
	Else,
	Export,
	Extends,
	False,
	Finally,
	For,
	Function,
	If,
	Import,
	In,
	Instanceof,
	New,
	Null,
	Return,
	Super,
	Switch,
	This,
	Throw,
	True,
	Try,
	Typeof,
	Var,
	Void,
	While,
	With,
}

impl Keyword {
	pub(crate) fn from_word(word: &str) -> Option<Keyword> {
		use Keyword::*;
		let bytes = word.as_bytes();
		if !(2..=10).contains(&bytes.len())
			|| !matches!(
				bytes[0],
				b'b' | b'c' | b'd' | b'e' | b'f' | b'i' | b'n' | b'r' | b's' | b't' | b'v' | b'w'
			) {
			return None;
		}
		Some(match word {
			"break" => Break,
			"case" => Case,
			"catch" => Catch,
			"class" => Class,
			"const" => Const,
			"continue" => Continue,
			"debugger" => Debugger,
			"default" => Default,
			"delete" => Delete,
			"do" => Do,
			"else" => Else,
			"export" => Export,
			"extends" => Extends,
			"false" => False,
			"finally" => Finally,
			"for" => For,
			"function" => Function,
			"if" => If,
			"import" => Import,
			"in" => In,
			"instanceof" => Instanceof,
			"new" => New,
			"null" => Null,
			"return" => Return,
			"super" => Super,
			"switch" => Switch,
			"this" => This,
			"throw" => Throw,
			"true" => True,
			"try" => Try,
			"typeof" => Typeof,
			"var" => Var,
			"void" => Void,
			"while" => While,
			"with" => With,
			_ => return None,
		})
	}

	pub(crate) fn as_str(self) -> &'static str {
		use Keyword::*;
		match self {
			Break => "break",
			Case => "case",
			Catch => "catch",
			Class => "class",
			Const => "const",
			Continue => "continue",
			Debugger => "debugger",
			Default => "default",
			Delete => "delete",
			Do => "do",
			Else => "else",
			Export => "export",
			Extends => "extends",
			False => "false",
			Finally => "finally",
			For => "for",
			Function => "function",
			If => "if",
			Import => "import",
			In => "in",
			Instanceof => "instanceof",
			New => "new",
			Null => "null",
			Return => "return",
			Super => "super",
			Switch => "switch",
			This => "this",
			Throw => "throw",
			True => "true",
			Try => "try",
			Typeof => "typeof",
			Var => "var",
			Void => "void",
			While => "while",
			With => "with",
		}
	}
}
