use crate::interner::StrId;

#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct Token {
	pub(crate) kind: TokenKind,
	pub(crate) start: u32,
	pub(crate) end: u32,
	pub(crate) newline_before: bool,
	/// An identifier or keyword written with a unicode escape.
	pub(crate) escaped: bool,
}

impl Token {
	pub(crate) fn eof(pos: u32) -> Token {
		Token {
			kind: TokenKind::Eof,
			start: pos,
			end: pos,
			newline_before: false,
			escaped: false,
		}
	}
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) enum TokenKind {
	Eof,
	Ident(StrId),
	PrivateName(StrId),
	Keyword(Keyword),
	Number(f64),
	BigInt,
	String(StrId),
	Template {
		cooked: Option<StrId>,
		raw: StrId,
		tail: bool,
	},
	RegExp {
		pattern: StrId,
		flags: StrId,
	},

	BraceL,
	BraceR,
	ParenL,
	ParenR,
	BracketL,
	BracketR,
	Semi,
	Comma,
	Dot,
	Ellipsis,
	Question,
	QuestionDot,
	Colon,
	Arrow,
	Backquote,
	At,

	Eq,
	PlusEq,
	MinusEq,
	StarEq,
	SlashEq,
	PercentEq,
	StarStarEq,
	LtLtEq,
	GtGtEq,
	GtGtGtEq,
	AmpEq,
	PipeEq,
	CaretEq,
	AmpAmpEq,
	PipePipeEq,
	QuestionQuestionEq,

	EqEq,
	BangEq,
	EqEqEq,
	BangEqEq,
	Lt,
	Gt,
	LtEq,
	GtEq,
	LtLt,
	GtGt,
	GtGtGt,
	Plus,
	Minus,
	Star,
	Slash,
	Percent,
	StarStar,
	Amp,
	Pipe,
	Caret,
	AmpAmp,
	PipePipe,
	QuestionQuestion,
	Bang,
	Tilde,
	PlusPlus,
	MinusMinus,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Keyword {
	Break,
	Case,
	Catch,
	Class,
	Const,
	Continue,
	Debugger,
	Default,
	Delete,
	Do,
	Else,
	Export,
	Extends,
	False,
	Finally,
	For,
	Function,
	If,
	Import,
	In,
	Instanceof,
	New,
	Null,
	Return,
	Super,
	Switch,
	This,
	Throw,
	True,
	Try,
	Typeof,
	Var,
	Void,
	While,
	With,
}

impl Keyword {
	pub(crate) fn from_word(word: &str) -> Option<Keyword> {
		use Keyword::*;
		Some(match word.len() {
			2 => match word {
				"do" => Do,
				"if" => If,
				"in" => In,
				_ => return None,
			},
			3 => match word {
				"for" => For,
				"new" => New,
				"try" => Try,
				"var" => Var,
				_ => return None,
			},
			4 => match word {
				"case" => Case,
				"else" => Else,
				"null" => Null,
				"this" => This,
				"true" => True,
				"void" => Void,
				"with" => With,
				_ => return None,
			},
			5 => match word {
				"break" => Break,
				"catch" => Catch,
				"class" => Class,
				"const" => Const,
				"false" => False,
				"super" => Super,
				"throw" => Throw,
				"while" => While,
				_ => return None,
			},
			6 => match word {
				"delete" => Delete,
				"export" => Export,
				"import" => Import,
				"return" => Return,
				"switch" => Switch,
				"typeof" => Typeof,
				_ => return None,
			},
			7 => match word {
				"default" => Default,
				"extends" => Extends,
				"finally" => Finally,
				_ => return None,
			},
			8 => match word {
				"continue" => Continue,
				"debugger" => Debugger,
				"function" => Function,
				_ => return None,
			},
			10 => match word {
				"instanceof" => Instanceof,
				_ => return None,
			},
			_ => return None,
		})
	}

	pub(crate) fn as_str(self) -> &'static str {
		use Keyword::*;
		match self {
			Break => "break",
			Case => "case",
			Catch => "catch",
			Class => "class",
			Const => "const",
			Continue => "continue",
			Debugger => "debugger",
			Default => "default",
			Delete => "delete",
			Do => "do",
			Else => "else",
			Export => "export",
			Extends => "extends",
			False => "false",
			Finally => "finally",
			For => "for",
			Function => "function",
			If => "if",
			Import => "import",
			In => "in",
			Instanceof => "instanceof",
			New => "new",
			Null => "null",
			Return => "return",
			Super => "super",
			Switch => "switch",
			This => "this",
			Throw => "throw",
			True => "true",
			Try => "try",
			Typeof => "typeof",
			Var => "var",
			Void => "void",
			While => "while",
			With => "with",
		}
	}
}
