//! The strings a writer names itself, numbered once for the stream: a literal resolves to its
//! number at compile time through `c!`, and a string from outside the table, a host grammar's, gets
//! its number from the writer that meets it.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Name {
	/// The index in `NAMES`, or `u32::MAX` for a string outside it.
	pub id: u32,
	pub text: &'static str,
}

impl Name {
	/// A string met at run time, a host grammar's: the writer numbers it by its address.
	pub const fn dynamic(text: &'static str) -> Name {
		Name { id: u32::MAX, text }
	}

	/// A literal the table holds; `c!` evaluates it at compile time.
	pub const fn known(text: &'static str) -> Name {
		match find(text) {
			Some(id) => Name { id, text },
			None => panic!("a name the writer emits is missing from NAMES"),
		}
	}
}

macro_rules! c {
	($text:literal) => {
		const { $crate::names::Name::known($text) }
	};
}
pub(crate) use c;

/// The index of a name in `NAMES`.
pub const fn find(text: &str) -> Option<u32> {
	let bytes = text.as_bytes();
	let mut slot = hash(bytes);
	loop {
		let i = INDEX[slot];
		if i == u16::MAX {
			return None;
		}
		if same(NAMES[i as usize].as_bytes(), bytes) {
			return Some(i as u32);
		}
		slot = (slot + 1) % SLOTS;
	}
}

const fn same(a: &[u8], b: &[u8]) -> bool {
	if a.len() != b.len() {
		return false;
	}
	let mut i = 0;
	while i < a.len() {
		if a[i] != b[i] {
			return false;
		}
		i += 1;
	}
	true
}

const SLOTS: usize = 2048;

static INDEX: [u16; SLOTS] = {
	let mut slots = [u16::MAX; SLOTS];
	let mut i = 0;
	while i < NAMES.len() {
		let mut slot = hash(NAMES[i].as_bytes());
		while slots[slot] != u16::MAX {
			slot = (slot + 1) % SLOTS;
		}
		slots[slot] = i as u16;
		i += 1;
	}
	slots
};

const fn hash(bytes: &[u8]) -> usize {
	let mut h: u64 = 0;
	let mut i = 0;
	while i < bytes.len() {
		h = (h.rotate_left(5) ^ bytes[i] as u64).wrapping_mul(0x517c_c1b7_2722_0a95);
		i += 1;
	}
	(h >> 53) as usize
}

pub static NAMES: [&str; 536] = [
	"!",
	"!=",
	"!==",
	"%",
	"%=",
	"&",
	"&&",
	"&&=",
	"&=",
	"*",
	"**",
	"**=",
	"*=",
	"+",
	"++",
	"+=",
	"-",
	"--",
	"-=",
	"/",
	"/=",
	"<",
	"<<",
	"<<=",
	"<=",
	"=",
	"==",
	"===",
	">",
	">=",
	">>",
	">>=",
	">>>",
	">>>=",
	"??",
	"??=",
	"AccessorProperty",
	"ArrayExpression",
	"ArrayPattern",
	"ArrowFunctionExpression",
	"AssignmentExpression",
	"AssignmentPattern",
	"AwaitExpression",
	"BinaryExpression",
	"Block",
	"BlockStatement",
	"BreakStatement",
	"CallExpression",
	"CatchClause",
	"ChainExpression",
	"ClassBody",
	"ClassDeclaration",
	"ClassExpression",
	"ConditionalExpression",
	"ContinueStatement",
	"DebuggerStatement",
	"Decorator",
	"DoWhileStatement",
	"EmptyStatement",
	"ExportAllDeclaration",
	"ExportDefaultDeclaration",
	"ExportNamedDeclaration",
	"ExportSpecifier",
	"ExpressionStatement",
	"ForInStatement",
	"ForOfStatement",
	"ForStatement",
	"FunctionDeclaration",
	"FunctionExpression",
	"Identifier",
	"IfStatement",
	"ImportAttribute",
	"ImportDeclaration",
	"ImportDefaultSpecifier",
	"ImportExpression",
	"ImportNamespaceSpecifier",
	"ImportSpecifier",
	"LabeledStatement",
	"Line",
	"Literal",
	"LogicalExpression",
	"MemberExpression",
	"MetaProperty",
	"MethodDefinition",
	"NewExpression",
	"ObjectExpression",
	"ObjectPattern",
	"PrivateIdentifier",
	"Program",
	"Property",
	"PropertyDefinition",
	"RestElement",
	"ReturnStatement",
	"SequenceExpression",
	"SpreadElement",
	"StaticBlock",
	"Super",
	"SwitchCase",
	"SwitchStatement",
	"TSAnyKeyword",
	"TSArrayType",
	"TSAsExpression",
	"TSBigIntKeyword",
	"TSBooleanKeyword",
	"TSCallSignatureDeclaration",
	"TSConditionalType",
	"TSConstructSignatureDeclaration",
	"TSConstructorType",
	"TSDeclareFunction",
	"TSDeclareMethod",
	"TSEnumDeclaration",
	"TSEnumMember",
	"TSExportAssignment",
	"TSExpressionWithTypeArguments",
	"TSExternalModuleReference",
	"TSFunctionType",
	"TSImportEqualsDeclaration",
	"TSImportType",
	"TSIndexSignature",
	"TSIndexedAccessType",
	"TSInferType",
	"TSInstantiationExpression",
	"TSInterfaceBody",
	"TSInterfaceDeclaration",
	"TSIntersectionType",
	"TSIntrinsicKeyword",
	"TSLiteralType",
	"TSMappedType",
	"TSMethodSignature",
	"TSModuleBlock",
	"TSModuleDeclaration",
	"TSNamedTupleMember",
	"TSNamespaceExportDeclaration",
	"TSNeverKeyword",
	"TSNonNullExpression",
	"TSNullKeyword",
	"TSNumberKeyword",
	"TSObjectKeyword",
	"TSOptionalType",
	"TSParameterProperty",
	"TSParenthesizedType",
	"TSPropertySignature",
	"TSQualifiedName",
	"TSRestType",
	"TSSatisfiesExpression",
	"TSStringKeyword",
	"TSSymbolKeyword",
	"TSThisType",
	"TSTupleType",
	"TSTypeAliasDeclaration",
	"TSTypeAnnotation",
	"TSTypeAssertion",
	"TSTypeCastExpression",
	"TSTypeLiteral",
	"TSTypeOperator",
	"TSTypeParameter",
	"TSTypeParameterDeclaration",
	"TSTypeParameterInstantiation",
	"TSTypePredicate",
	"TSTypeQuery",
	"TSTypeReference",
	"TSUndefinedKeyword",
	"TSUnionType",
	"TSUnknownKeyword",
	"TSVoidKeyword",
	"TaggedTemplateExpression",
	"TemplateElement",
	"TemplateLiteral",
	"ThisExpression",
	"ThrowStatement",
	"TryStatement",
	"UnaryExpression",
	"UpdateExpression",
	"VariableDeclaration",
	"VariableDeclarator",
	"WhileStatement",
	"WithStatement",
	"YieldExpression",
	"^",
	"^=",
	"abstract",
	"abstract_outside_abstract_class",
	"abstract_placement",
	"abstract_with_implementation",
	"abstract_with_initializer",
	"accessibility",
	"accessor",
	"accessor_constructor",
	"accessor_in_pattern",
	"accessor_type_parameters",
	"alternate",
	"ambient_const_initializer",
	"argument",
	"arguments",
	"arguments_in_field_initializer",
	"asserts",
	"async",
	"async_constructor",
	"attributes",
	"await",
	"await using",
	"await_as_identifier",
	"await_in_default_value",
	"await_outside_async",
	"bad_character_escape",
	"bad_template_escape",
	"bigint",
	"binding",
	"binding_member_expression",
	"binding_parenthesized",
	"bindings",
	"block",
	"body",
	"callee",
	"cases",
	"catch",
	"catch_clause_type",
	"checkType",
	"class",
	"class-name",
	"code",
	"code_point_out_of_bounds",
	"column",
	"comma_after_rest",
	"comments",
	"computed",
	"conflicting_modifiers",
	"consequent",
	"const",
	"const_assertion_target",
	"constraint",
	"constructor",
	"constructor_field",
	"constructor_modifier",
	"constructor_return_type",
	"constructor_type_parameters",
	"cooked",
	"declaration",
	"declarations",
	"declare",
	"declare_in_ambient",
	"declare_on_method",
	"declares",
	"decorator_on_constructor",
	"decorator_placement",
	"decorator_without_body",
	"decorators",
	"default",
	"defines",
	"definite",
	"definite_with_initializer",
	"delegate",
	"delete",
	"delete_private",
	"directive",
	"discriminant",
	"duplicate",
	"duplicate_accessibility",
	"duplicate_constructor",
	"duplicate_default",
	"duplicate_export",
	"duplicate_import_attribute",
	"duplicate_label",
	"duplicate_modifier",
	"duplicate_parameter",
	"duplicate_proto",
	"duplicate_regexp_flag",
	"elementType",
	"elementTypes",
	"elements",
	"empty_list",
	"empty_type_arguments",
	"empty_type_parameters",
	"end",
	"enum",
	"enum-member",
	"errors",
	"escape_in_keyword",
	"expected",
	"expected_number_in_radix",
	"expected_unicode_escape",
	"exportKind",
	"export_assignment_in_namespace",
	"export_declare_without_declaration",
	"exported",
	"exprName",
	"expression",
	"expressions",
	"extends",
	"extendsType",
	"falseType",
	"finalizer",
	"flags",
	"for",
	"for_in_of_initializer",
	"for_of_let",
	"fragment",
	"function",
	"function-name",
	"generator",
	"generator_constructor",
	"generator_in_ambient",
	"generator_signature",
	"get",
	"getter_params",
	"global",
	"handler",
	"id",
	"identifier_after_number",
	"implementation_in_ambient",
	"implements",
	"import",
	"importKind",
	"import_export_in_script",
	"import_export_not_top_level",
	"import_meta_escaped",
	"import_meta_outside_module",
	"import_type_alias",
	"imported",
	"in",
	"indexType",
	"index_signature_modifier",
	"index_signature_type",
	"infer_placement",
	"init",
	"initializer",
	"initializer_in_ambient",
	"innerComments",
	"instanceof",
	"interface_without_name",
	"invalid_assignment_target",
	"invalid_binding_target",
	"invalid_const",
	"invalid_default_operator",
	"invalid_import_meta",
	"invalid_in_static_block",
	"invalid_name",
	"invalid_new_target",
	"invalid_number",
	"invalid_regexp",
	"invalid_regexp_flag",
	"invalid_request",
	"invalid_super",
	"invalid_unicode_escape",
	"isExport",
	"key",
	"kind",
	"label",
	"leadingComments",
	"left",
	"let",
	"let_as_binding",
	"line",
	"literal",
	"loc",
	"local",
	"members",
	"message",
	"meta",
	"method",
	"missing_catch_or_finally",
	"mixed_coalesce",
	"modifier_order",
	"module",
	"moduleReference",
	"mutate",
	"name",
	"nameType",
	"namespace",
	"nesting_depth",
	"new_target_escaped",
	"new_target_outside_function",
	"newline_after_throw",
	"no error for {src:?}",
	"node",
	"not_typescript",
	"numeric_separator_double",
	"numeric_separator_first",
	"numeric_separator_last",
	"numeric_separator_legacy_octal",
	"object",
	"objectType",
	"operator",
	"optional",
	"optional_chain_assignment",
	"optional_chain_in_new",
	"optional_chain_in_tagged_template",
	"optional_pattern_parameter",
	"optional_rest",
	"optional_with_initializer",
	"options",
	"out",
	"override",
	"override_without_extends",
	"param",
	"parameter",
	"parameterName",
	"parameter_property_pattern",
	"parameters",
	"params",
	"parent",
	"parenthesized",
	"parenthesized_pattern",
	"pattern",
	"pattern_without_initializer",
	"placement",
	"pos",
	"predicate_placement",
	"prefix",
	"private",
	"private_constructor",
	"private_modifier",
	"private_name_outside_in",
	"properties",
	"property",
	"property_after_instantiation",
	"protected",
	"public",
	"qualifier",
	"quasi",
	"quasis",
	"quoted_module_name",
	"raw",
	"read",
	"readonly",
	"readonly_on_method",
	"readonly_placement",
	"readonly_type_operand",
	"redeclaration",
	"reference",
	"references",
	"regex",
	"required_after_optional",
	"reserved_word",
	"rest_with_default",
	"returnType",
	"return_outside_function",
	"right",
	"root",
	"roots",
	"scope",
	"scopes",
	"script",
	"set",
	"setter_optional_parameter",
	"setter_parameter_initializer",
	"setter_params",
	"setter_rest_param",
	"setter_return_type",
	"shorthand",
	"shorthand_assignment",
	"signature_parameter_default",
	"source",
	"sourceType",
	"specifiers",
	"start",
	"statement_in_ambient",
	"static",
	"static-block",
	"static_block_modifier",
	"static_prototype",
	"strict_binding",
	"strict_delete",
	"strict_directive_non_simple_params",
	"strict_escape",
	"strict_octal",
	"strict_with",
	"string_export_without_from",
	"superClass",
	"superTypeParameters",
	"super_call_outside_constructor",
	"super_outside_method",
	"switch",
	"tag",
	"tail",
	"test",
	"this_parameter_modifiers",
	"topLevelAwait",
	"trailingComments",
	"tree_size",
	"trueType",
	"tuple_label",
	"type",
	"typeAnnotation",
	"typeArguments",
	"typeName",
	"typeParameter",
	"typeParameters",
	"type_annotation_after_default",
	"type_import_argument",
	"type_import_default_and_named",
	"type_member_modifier",
	"type_modifier_in_type_import",
	"type_parameter_modifier",
	"type_redeclaration",
	"typeof",
	"types",
	"typescript",
	"unclosed",
	"undeclared_private_name",
	"undefined_export",
	"unexpected_character",
	"unexpected_close",
	"unexpected_eof",
	"unexpected_keyword",
	"unexpected_token",
	"unexpected_type_annotation",
	"unsyntactic",
	"unterminated_comment",
	"unterminated_regexp",
	"unterminated_string",
	"unterminated_template",
	"update",
	"using",
	"using_in_ambient",
	"using_in_for_in",
	"using_outside_block",
	"using_pattern",
	"using_without_initializer",
	"value",
	"var",
	"void",
	"with",
	"write",
	"writes",
	"yield_as_identifier",
	"yield_in_default_value",
	"{kind:?}",
	"{path}: {e}",
	"{src:?}: {e}",
	"{src}: {e}",
	"|",
	"|=",
	"||",
	"||=",
	"~",
];
