/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Source {
  constructor(source: Uint8Array, options: string)
  parse(entry: number, offset: number, end: number | undefined | null, stop: string): Uint32Array | string
}

export declare function constants(): Array<string>

export declare function shapes(): Array<number>
