/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A source held with its switches, so many parses out of it pay for its tables once. */
export declare class Source {
  constructor(source: string, bits: number)
  parseAt(entry: number, offset: number, until: boolean): Answer
  /** The program spanning `start..end` of the source, `end` defaulting to its end. */
  parseRange(start: number, end?: number | undefined | null): Answer
}

/** The constant strings numbered so far, which a token stream refers to by id. */
export declare function constants(): Array<string>

/**
 * One parse of `entry` (`json::Entry` by index) at a UTF-16 `offset`; `until` says the host's
 * `as` follows the expression.
 */
export declare function parseAt(source: string, bits: number, entry: number, offset: number, until: boolean): Answer

/** The same answer as JSON text, for checking the decoder against. */
export declare function parseAtJson(source: string, bits: number, entry: number, offset: number, until: boolean): string
